### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by aptgetdev** [pixeldothorse/pixel.horse#125]
bootstrap-05949a50bc.js:2 Uncaught ReferenceError: exports is not defined
    at bootstrap-05949a50bc.js:2
what does that suppose to mean?

**Comment by BytewaveMLP** [comment]
Do you run your own instance, or is this from a live server?

**Comment by aptgetdev** [comment]
my own instance from linode

**Comment by BytewaveMLP** [comment]
Did your compilation succeed without errors? Did you make sure to run `npm run build-init` for your first build?

**Comment by aptgetdev** [comment]
i did npm i
the npm run build
then npm start
